### ISSUE TITLE
Implementation dependencies in local projects are not considered jar classes

### ISSUE THREAD

**Issue by lwasyl** [slackhq/keeper#18] opened 2020-01-30 02:57 UTC
**Keeper version:** 0.1.0
**Kotlin version:** 1.3.61

I just tried Keeper on our project and it seems to not be working, as I get this error when running the tests:
```
E/AndroidJUnit4Builder: Error constructing runner
java.lang.IncompatibleClassChangeError: Couldn't find kotlin.Metadata.bv
    at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
    at libcore.reflect.AnnotationAccess.annotationSetToAnnotations(AnnotationAccess.java:633)
    at libcore.reflect.AnnotationAccess.getDeclaredAnnotations(AnnotationAccess.java:161)
    at libcore.reflect.AnnotationAccess.getAnnotations(AnnotationAccess.java:111)
    at java.lang.Class.getAnnotations(Class.java:369)
    at org.junit.runners.model.TestClass.getAnnotations(TestClass.java:215)
    at org.junit.validator.AnnotationsValidator$AnnotatableValidator.validateAnnotatable(AnnotationsValidator.java:62)
    at org.junit.validator.AnnotationsValidator$AnnotatableValidator.validateTestClass(AnnotationsValidator.java:54)
    at org.junit.validator.AnnotationsValidator.validateTestClass(AnnotationsValidator.java:36)
    at org.junit.runners.ParentRunner.applyValidators(ParentRunner.java:134)
    at org.junit.runners.ParentRunner.collectInitializationErrors(ParentRunner.java:128)
    at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:124)
    at org.junit.runners.ParentRunner.validate(ParentRunner.java:416)
    at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)
    at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
    at androidx.test.internal.runner.junit4.AndroidJUnit4ClassRunner.<init>(AndroidJUnit4ClassRunner.java:43)
    at androidx.test.internal.runner.junit4.AndroidJUnit4Builder.runnerForClass(AndroidJUnit4Builder.java:65)
    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
    at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
    at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:153)
    at androidx.test.internal.runner.TestLoader$ScanningRunnerBuilder.runnerForClass(TestLoader.java:143)
    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
    at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:73)
    at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
    at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:793)
    at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:547)
    at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:390)
    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
```

Previously I was actually working on running UI tests on an obfuscated variant and finally reached a point where tests would start, but tons of methods were missing. So I applied Keeper and got the above error. It's thrown before any actual test code is ran, while without it tests crash on first method not added to the proguard file, but already somewhere in the test sources. It seems Kotlin metadata annotations are stripped when using Keeper but aren't stripped without it 🤔

I can see the following entry in the `inferredUsage.pro` file:
```proguard
-keep interface kotlin.Metadata {
  public java.lang.String[] d1();
  public java.lang.String[] d2();
  public int[] mv();
  public int xi();
}
```

and I have no other manual Kotlin-related rules in proguard-rules.pro (perhaps there's something in Android-default rules though)

**Comment by ZacSweers** [comment] 2020-01-30 17:14
Do you use kotlin-reflect in your app?

**Comment by ZacSweers** [comment] 2020-01-30 17:29
Also - what proguard rules (if any) do you use for the test variant? i.e. `testProguardFile(...)`

**Comment by lwasyl** [comment] 2020-01-30 17:41
The only reflect import I use in the app is `kotlin.reflect.KClass`. In tests I don't think any reflect calls are made, but there is in fact a stray kotlin-reflect dependency in androidTest. No dependency in main source set though.

When I removed the reflect dependency from tests I started seeing an error about a missing method in one of the test rules (class used in main sources, method only in tests). It's already a bit in the execution though, so some methods were definitely picked up by Keeper.

I don't have a test proguard file. What would I normally need there?

**Comment by ZacSweers** [comment] 2020-01-30 17:49
So without that, it will also try to minify your tests with the same proguard rules (iirc). Internally we don’t care about minifying test sources though, so we specify a test proguard rule that basically disables everything (dontoptimize, dontobfuscate, etc). I can paste our file contents for this in a bit.

What’s the new error you get once reflect is removed?

**Comment by lwasyl** [comment] 2020-01-30 19:05
I don't have exact error atm but it couldn't find `boolean ApolloClient#clearNormalizedCache()` method. I'm not quite sure I follow though, since this error happens quite far in our rule chain, and without Keeper tests would crash much earlier, on an analogous method: `org.threeten.bp.Clock#fixed`. So just like Apollo is used in main sources but `clearNormalizedCache` isn't, `Clock` is also used in main sources, but `fixed` method isn't. What's the difference?

>  test proguard rule that basically disables everything (dontoptimize, dontobfuscate, etc). I can paste our file contents for this in a bit.

That'd be nice :) I also don't care about obfuscating test APK (other than what's required for it to work with obfuscated main APK)

**Comment by ZacSweers** [comment] 2020-01-30 20:54
Here's what we do for our test proguard config (basically to tell proguard/R8 to not touch androidTest sources + ignore some warnings from test libraries)

```
# Proguard rules that are applied to your test apk/code.
-dontskipnonpubliclibraryclassmembers
-dontoptimize
-dontobfuscate
-dontshrink
-ignorewarnings
-dontnote **
-dontwarn org.easymock.IArgumentMatcher
-dontwarn org.mockito.internal.creation.bytebuddy.MockMethodDispatcher
-dontwarn org.jmock.core.Constraint
-dontwarn org.robolectric.RobolectricTestRunner
-dontwarn org.objectweb.asm.ClassVisitor
-dontwarn javax.servlet.ServletContextListener
-dontwarn java.lang.instrument.ClassFileTransformer
-dontwarn org.objectweb.asm.MethodVisitor
-dontwarn android.net.http.**
-dontwarn com.android.internal.http.multipart.MultipartEntity
```

I'd recommend trying that in your config and see if it still happens

Example

```groovy
android {
  buildTypes {
    release {
      testProguardFile('testrules.pro')
    }
  }
}
```

**Comment by lwasyl** [comment] 2020-01-30 23:23
Unfortunately, no luck :( But I'm still not sure I understand - shouldn't Keeper see that I use that method and add an appropriate rule? Seeing as it's a regular dependency used from androidTest source set.

Btw the error is `No virtual method clearNormalizedCache()Z in class Lcom/apollographql/apollo/ApolloClient; or its super classes`. If I add a rule for it in `proguard-rules` (main): `-keep class com.apollographql.apollo.ApolloClient { boolean clearNormalizedCache(); }` then tests go through that specific place (although they crash not long after).

**Comment by ZacSweers** [comment] 2020-01-30 23:34
Keeper infers what androidTest sources (and its unique dependencies) use from the target app variant (and its dependencies). Your stacktrace appeared initially to be a crash in your androidTest sources, which seemed to imply proguard was stripping androidTest-only dependencies (and I think was in fact the case).

As for why it fails later, unfortunately there's not much we can do to help at this point without a reproducible sample, as there could be a number of other factors in your build that may influence this :/.

**Comment by ZacSweers** [comment] 2020-01-31 00:14
Talked with @lwasyl in the KotlinLang slack and we've figured out what the issue is: keeper composes a classpath based on the javacompile/kotlincompile tasks' classpath, but it seems that these are incomplete if the app depends on a local project dependency that includes an implementation dependency that is used by android tests.

Example:
- project `library` with implementation dep `networking`
- app implementation dep on `library`
- androidTest implementation dep on `networking`

Problem - `networking` is incorrectly seen as an `androidTest`-only dependency and not considered during rule inference

**Comment by ZacSweers** [comment] 2020-01-31 00:43
@pyricau has a public repro case for this on leakcanary that I'll look into. Slightly different as the dependency is a transitive of androidTest as well, but same underlying issue with `implementation`

```
git pull
git checkout -b py/keeper
./gradlew leakcanary-android-sample:connectedCheck -Pminify
```

**Comment by ZacSweers** [comment] 2020-02-03 02:08
Ok the leakcanary repro case was actually a different issue, and unfortunately recreating the above conditions in #21 appears to work fine :/

**Comment by ZacSweers** [comment] 2020-02-03 09:34
Closing this out again for now after talking more on the kotlin lang slack, keeper appears to be working correctly in all the cases we can test so far and @lwasyl also isn’t able to repro anymore.

**Closed by ZacSweers** 2020-02-03 09:34 UTC
Labels: bug
